version: "3.7"

services:
  frontend:
    image: "arjunsingh751/eti-ooper-frontend"
    ports:
      - 8080:8080

  auth-microservice:
    image: "arjunsingh751/eti-ooper-auth"
    ports:
      - 5003:5003
    environment:
      DRIVER_MS_HOST: http://driver-microservice:5001
      PASSENGER_MS_HOST: http://passenger-microservice:5000
      ENVIRONMENT: "production"

  passenger-microservice:
    image: "arjunsingh751/eti-ooper-passenger"
    ports:
      - 5000:5000
    environment:
      MYSQL_HOST: passenger-db
      DATABASE_NAME: "passengers"
      AUTH_MS_HOST: http://auth-microservice:5003
      ENVIRONMENT: "production"
  passenger-db:
    image: mysql:latest
    volumes:
      - type: bind
        source: "./Passenger Account Microservice/passenger.sql"
        target: /docker-entrypoint-initdb.d/passenger.sql
    ports:
      - 3000:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: passengers

  driver-microservice:
    image: "arjunsingh751/eti-ooper-driver"
    ports:
      - 5001:5001
    environment:
      MYSQL_HOST: driver-db
      DATABASE_NAME: "drivers"
      AUTH_MS_HOST: http://auth-microservice:5003
      ENVIRONMENT: "production"
  driver-db:
    image: mysql:latest
    volumes:
      - type: bind
        source: "./Driver Account Microservice/driver.sql"
        target: /docker-entrypoint-initdb.d/driver.sql
    ports:
      - 3301:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: drivers

  trip-microservice:
    image: "arjunsingh751/eti-ooper-trip"
    ports:
      - 5004:5004
    environment:
      MYSQL_HOST: trip-db
      DATABASE_NAME: "trips"
      DRIVER_MS_HOST: http://driver-microservice:5001
      AUTH_MS_HOST: http://auth-microservice:5003
      ENVIRONMENT: "production"
  trip-db:
    image: mysql:latest
    ports:
      - 3304:3306
    volumes:
      - type: bind
        source: "./Trips Microservice/trip.sql"
        target: /docker-entrypoint-initdb.d/trip.sql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: trips
