# syntax=docker/dockerfile:1
#
## Build
##

FROM golang:1.16-alpine AS build
WORKDIR /app
# Copy go module files to download all required modules
COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY main.go ./

#Bulid file as "auth" and run
RUN CGO_ENABLED=0 go build -o /auth


##
## Deploy
##

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /auth /auth

EXPOSE 5003

USER nonroot:nonroot

ENTRYPOINT ["/auth"]