# syntax=docker/dockerfile:1
## Build application

FROM golang:1.16-alpine as BUILD
WORKDIR /app

# Copy go module files to download all required modules
COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY main.go ./

#Bulid file as "trip" and run
RUN CGO_ENABLED=0 go build -o /trip

# ## Deploy app using distroless image
FROM gcr.io/distroless/base-debian10
WORKDIR /

COPY --from=build /trip /trip

EXPOSE 5004

USER nonroot:nonroot

ENTRYPOINT ["/trip"]